/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 3.4.2 -fPIC -Os) */

(* src = "design.sv:2" *)
module spi_slave(SCLK, MOSI, SS, din, mode, MISO);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  (* src = "design.sv:6" *)
  output MISO;
  (* src = "design.sv:3" *)
  input MOSI;
  (* src = "design.sv:3" *)
  input SCLK;
  (* src = "design.sv:3" *)
  input SS;
  (* src = "design.sv:4" *)
  input [7:0] din;
  (* src = "design.sv:8" *)
  reg [7:0] memory;
  (* src = "design.sv:9" *)
  reg misoreg;
  (* src = "design.sv:5" *)
  input [1:0] mode;
  assign _01_ = ~ (* src = "design.sv:18" *) SCLK;
  assign _05_ = | (* src = "design.sv:18" *) { SCLK, _12_ };
  assign _09_ = | (* src = "design.sv:18" *) { _13_, _14_ };
  assign _10_ = | (* src = "design.sv:18" *) { SCLK, _15_ };
  assign _11_ = | (* src = "design.sv:18" *) { _16_, _17_ };
  assign _03_ = _01_ & (* src = "design.sv:18" *) mode[0];
  assign _04_ = _01_ & (* src = "design.sv:18" *) _03_;
  assign _12_ = _01_ & (* src = "design.sv:18" *) _04_;
  assign _06_ = _01_ & (* src = "design.sv:18" *) _05_;
  assign _13_ = _01_ & (* src = "design.sv:18" *) _06_;
  assign _08_ = SCLK & (* src = "design.sv:18" *) _07_;
  assign _14_ = SCLK & (* src = "design.sv:18" *) _08_;
  assign _15_ = _01_ & (* src = "design.sv:18" *) _07_;
  assign _16_ = _01_ & (* src = "design.sv:18" *) _10_;
  assign _17_ = SCLK & (* src = "design.sv:18" *) mode[0];
  always @*
    if (_02_)
      memory = { MOSI, memory[7:1] };
  assign _02_ = ~ _11_;
  always @*
    if (_00_)
      misoreg = memory[0];
  assign _00_ = ~ _09_;
  assign _07_ = ~ (* src = "design.sv:26" *) mode[0];
  always @(negedge SS)
      memory <= din;
  always @(negedge SS)
      misoreg <= din[0];
  assign MISO = SS ? (* src = "design.sv:10" *) 1'hz : misoreg;
endmodule
